version: '3'
services:
  mongo-db:
    image: mongo:latest
    container_name: mongodb
    #network_mode: "host"
    restart: always
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/db:/data/db
      - ./backup:/data/backup
      - ./conf:/data/configdb
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"