version: '3'
services:
  rabbitmq:
    hostname: myrabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    volumes:
      - ./data:/var/lib/rabbitmq