filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/local/workspace/elk/filebeat/logstash-tutorial.log

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

#output.elasticsearch:
#  hosts: ["192.168.20.101:9200","192.168.20.101:9201"]
output.logstash:
  hosts: ["elk-logstash:5044"]