# jaeger
version: '3.1'
services:
  db:
    image: jaegertracing/all-in-one
    restart: always
    command:
      # 暴露Metrics端口号 默认14269
      - --admin-http-port=14269
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14269:14269
