# 全局配置
global:
  # 数据采集间隔
  scrape_interval: 5s
  # 监控检查间隔
  evaluation_interval: 5s

# 报警规则
rule_files:
# - "first.rules"
# - "second.rules"

# 采集任务
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: jaeger
    static_configs:
      - targets:
          - localhost:14269
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9101